const fruits = ["apple", "banana", "orange", "grape", "kiwi"];
console.log(fruits);
console.log(fruits.length);
console.log(fruits[2]);
console.log(fruits[fruits.length - 1]);
const vegetables = [];
let inputVegetable = prompt("Enter a vegetable");
vegetables.push(inputVegetable);
let inputVegetable2 = prompt("Enter a vegetable");
vegetables.push(inputVegetable2);
let inputVegetable3 = prompt("Enter a vegetable");
vegetables.push(inputVegetable3);
console.log(vegetables);
console.log(vegetables.length);
